### ISSUE TITLE
resolving for any output format other then 'human' fails

### ISSUE THREAD

**Issue by AdamJel** [wimglenn/johnnydep#105]
Hi,

I have a local .whl dist, for which I need to find dependencies. (I want to "reverse engineer" it to source project). Trying `johnnydep --output-format human <whl>` works and gives dependency tree. But any other output format ends in error.

'human':
```
├── certifi                     Python package for providing Mozilla's CA Bundle.
├── python-dateutil             Extensions to the standard Python datetime module
│   └── six>=1.5                Python 2 and 3 compatibility utilities
├── six>=1.10                   Python 2 and 3 compatibility utilities
```

'toml':
```
Traceback (most recent call last):
  ...
  File "<path>/pipx/venvs/johnnydep/lib/python3.10/site-packages/johnnydep/lib.py", line 362, in flatten_deps
    raise JohnnyError(msg.format(dist.name, dist.specifier))
johnnydep.lib.JohnnyError: Could not find satisfactory version for <whl>
```

'pinned':
```
Traceback (most recent call last):
  ...
  File "<path>/pipx/venvs/johnnydep/lib/python3.10/site-packages/johnnydep/lib.py", line 239, in pinned
    raise JohnnyError("Can not pin because no version available is in spec")
johnnydep.lib.JohnnyError: Can not pin because no version available is in spec
```

From 'human' output, there are no version specifications for 'certify' and 'python-dateutil'. Can this be the cause? If so, perhaps, the johnnydep could have a more understandable error msg. It would be greatly helpful if johnnydep still produced an output, even if omitting versions for those packages.

Also, it would be great, if one of possible outputs was requirements.txt file, with only 1. level dependencies with version constraints (not pinned). That is without deps of deps. This way, this requirements.txt file could be passed into other dependency manager, e.g. 'poetry' or 'pdm' and further processed.

**Comment by wimglenn** [comment]
To help with your issue I'll need to see the full dependency tree, or link me to a copy of the .whl file. As described, the issue is not reproducible.

> From 'human' output, there are no version specifications for 'certify' and 'python-dateutil'. Can this be the cause?

No. That just means the versions aren't constrained, i.e. any version will do.

> Also, it would be great, if one of possible outputs was requirements.txt file, with only 1. level dependencies with version constraints (not pinned). That is without deps of deps.

These are just the direct dependencies + constraints. It is already possible to print those using the "requires" field:

```
$ johnnydep --no-deps requests -f requires -o json
2023-01-15 19:29:50 [info     ] init johnnydist                [johnnydep.lib] dist=requests parent=None
[
  {
    "requires": [
      "certifi>=2017.4.17",
      "charset-normalizer<4,>=2",
      "idna<4,>=2.5",
      "urllib3<1.27,>=1.21.1"
    ]
  }
]
```

And actually you don't need to download the package at all in some cases, you can use the JSON api of the index:

```
curl -s https://pypi.org/pypi/requests/json | jq ".info.requires_dist"
[
  "charset-normalizer (<4,>=2)",
  "idna (<4,>=2.5)",
  "urllib3 (<1.27,>=1.21.1)",
  "certifi (>=2017.4.17)",
  "PySocks (!=1.5.7,>=1.5.6) ; extra == 'socks'",
  "chardet (<6,>=3.0.2) ; extra == 'use_chardet_on_py3'"
]
```

**Comment by AdamJel** [comment]
> Hi @AdamJel - to help with your issue I'll need to see the full dependency tree, or link me to a copy of the .whl file. As described, the issue is not reproducible.

Hi, thank you for a quick reply. Unfortunately, the .whl file is legally protected and I am not allowed to share it with anybody. Bummer, I know..

The complete list of deps:

```
<package>                       <description>
├── certifi                     Python package for providing Mozilla's CA Bundle.
├── python-dateutil             Extensions to the standard Python datetime module
│   └── six>=1.5                Python 2 and 3 compatibility utilities
├── six>=1.10                   Python 2 and 3 compatibility utilities
└── urllib3>=1.15               HTTP library with thread-safe connection pooling, file post, and more.
```

> These are just the direct dependencies + constraints. It is already possible to print those using the "requires" field:

Perfect, I missed this option / didn't realize I could use like this.

FYI, `johnnydep --no-deps <my-package> -f requires -o json` works just fine (no error). With 'pinned', error again.

On the subject, having the json output like that, is there a straightforward way how to use it with pip? I don't see any import / convert option within pip itself. Of course, such an output may be text processed into requirements.txt with not much effort, but if such option already exists within some tool, that would be even simpler.

**Comment by wimglenn** [comment]
@AdamJel OK, I understand what's happening now, it's because you're using a local wheel file and it is not available in the index (PyPI), so when johnnydep goes to check for available versions there is nothing found there. I was able to reproduce this and fixed it in [v1.17.2](https://pypi.org/project/johnnydep/1.17.2/), so try updating johnnydep to latest and let me know if that resolves the issue.

**Comment by AdamJel** [comment]
Yes, your fix works. All output formats work now. Quick response, immediate fix, thank you so much. This is open source community at its best. If you had active sponsoring option here, I'd buy you a coffee.

> No there isn't, and I consider it out of scope for johnnydep. It should only be a couple of lines of Python code to convert into a [requirements file format](https://pip.pypa.io/en/stable/reference/requirements-file-format/) though.

Why out of scope? johnnydep is for getting information about project dependencies, and these are very often described in requirements file (in {all cases} - {PEP-621 projects}). It seems rather fitting.

**Comment by wimglenn** [comment]
@AdamJel 

> This is open source community at its best. If you had active sponsoring option here, I'd buy you a coffee.

Thanks for the kind words. I've just switched on the [sponsorship](https://github.com/sponsors/wimglenn) option for my profile, if you still want to do that (don't feel obliged).

> Why out of scope?

Mostly because it's already possible easily, for example:

    python3 -c 'for req in __import__("johnnydep").JohnnyDist(mypkg).requires: print(req)'

Or using pkginfo (pip install pkginfo) may be even faster, e.g.

    pkginfo myfile.whl -f requires_dist --sequence-delim=$'\n' --single

> Is it possible / desirable to be able to set an alternative (internal) python registry?

Yes, this is possible using the [`--index-url`](https://github.com/wimglenn/johnnydep/blob/v1.17.2/johnnydep/cli.py#L44) option. It is also possible to use a local directory as an "index" without needing to run a web server, for information about how to do that refer to [How do install packages from a local python package index?](https://stackoverflow.com/q/45744937/674039) I have found the [piprepo](https://github.com/colinhoglund/piprepo) project useful for converting a local directory of release files into the correct structure to use as a [Simple Repository](https://peps.python.org/pep-0503/) index.
