### ISSUE TITLE
Pin installed version instead of the latest one

### ISSUE THREAD

**Issue by ftersin** [wimglenn/johnnydep#16]
I'd like to see installed versions in pinned mode to get requirements.txt to reproduce the environment somewhere else.
```
(venv3) johnnydep -f name version_installed -o pinned pandas --no-deps
pandas==0.23.3
(venv3) johnnydep -f name version_installed -o toml pandas --no-deps
name = "pandas"
version_installed = "0.22.0"
```

**Comment by wimglenn** [comment]
This functionality is already provided by `pip freeze`.  johnnydep pinned output is for latest version spec.

**Comment by ftersin** [comment]
Right, but ```pip freeze``` cannot return the subset of installed packages required by the specified package only.

**Comment by wimglenn** [comment]
That's true, but johnnydep does not require the packages to be installed. So it can not pin all requirements at the versions installed (because some of the requirements might not be installed at all). Workaround for your use case: you could use johnnydep to get the list of names, and then use these names to filter the `pip freeze` output accordingly.
