### ISSUE TITLE
Gracefully recover from errors

### ISSUE THREAD

**Issue by sbliven** [wimglenn/johnnydep#54]
It would be nice if johnnydep could recover from errors that occur while recursing (eg #53). Instead of dying with a stack trace, maybe indicate an error occurred at a particular branch and then continue displaying the rest of the tree?

**Comment by wimglenn** [comment]
It will be impossible to resolve the dependency tree if a build fails at any node. And it will be impossible to render the full tree correctly if a build fails (e.g. there may be more nodes underneath the failed build, which in turn constrain other sections of the tree). However, I suppose that is not necessarily a blocker here if the user didn't specifically request to solve the tree. I'll consider adding an option for this use case.

**Comment by sbliven** [comment]
Thanks! That would be useful.

**Comment by bjfar** [comment]
This feature would be extremely useful for debugging installation problems when developing packages. For example say I am trying to port my package to a newer version of Python: often this breaks things in the install because some packages that I depend on one way or another are not compatible with this newer Python version. So they fail to install. But sometimes the dependency is only a weak one, and I can avoid it by just switching some things around in my package. But to solve it I really need to know the exact way in which my package ultimately depended on the broken one. So it would be extremely useful to be able to show as much of the tree as possible. I cannot find any tools out there to do this, and yours is about the closest I have found.

**Comment by wimglenn** [comment]
Closed by https://github.com/wimglenn/johnnydep/pull/77
